formatter: markdown table

output:
  file: README.md
  mode: replace
  template: |
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  hide-empty: true
  # Disable raw HTML in markdown
  anchor: false
  html: false
