#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

terraform-docs terraform && git add terraform/README.md
yarn pretty-quick --staged
tflint

yarn concurrently "nx workspace-lint" "nx format:check"
yarn nx affected --target=lint
yarn nx affected --target=test --code-coverage
