name: Renovate

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  validate:
    name: Validate renovate config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: volta-cli/action@v4

      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: .github/renovate.json
