name: Terraform

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

defaults:
  run:
    working-directory: terraform

jobs:
  tflint:
    name: Lint and document terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Cache plugin dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          github_token: ${{ secrets.TFLINT_GITHUB_TOKEN }}

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.TFLINT_GITHUB_TOKEN }}

      - name: Run TFLint
        run: tflint -f compact

      - name: Check/update terraform-docs
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: terraform
          fail-on-diff: 'true'
          git-push: ${{ github.ref_name == 'main' && github.event_name == 'push' && 'false' || 'true' }}
          git-commit-message: 'docs(terraform): update README'
